### ISSUE TITLE
writeZone does not work when importing as flake

### ISSUE THREAD

**Issue by AluisioASG** [kirelagin/nix-dns#4]
`writeZone` relies on `pkgs.writeTextFile`, which is only available when the full `nixpkgs` is instantiated (`import "${nixpkgs}" { system = "some-system"; }`). It's simple enough a wrapper that I can just call `writeTextFile` myself, but I guess it should be documented somewhere along with `writeZone` itself.

**Comment by ncfavier** [comment]
> `writeZone` relies on `pkgs.writeTextFile`, which is only available when the full `nixpkgs` is instantiated (`import "${nixpkgs}" { system = "some-system"; }`).

What do you mean? How are you importing `dns/default.nix`?

**Comment by AluisioASG** [comment]
Here's a minimal example:

```nix
{
  inputs.nixpkgs.url = "github:NixOS/nixpkgs/nixpkgs-unstable";
  inputs.dns = { url = "github:kirelagin/nix-dns"; inputs.nixpkgs.follows = "nixpkgs"; };
  outputs = { self, nixpkgs, dns }: {
    defaultPackage.x86_64-linux = dns.lib.writeZone "example.invalid" {
      SOA = { nameServer = "ns.example.invalid"; adminEmail = "noc@example.invalid"; serial = 1; };
    };
  };
}
```

`nix build` results in:

```
error: --- EvalError ----------------------------------------------------------------- nix
at: (32:5) in file: /nix/store/lnphin86szjd22maxjcj51kk13gf34nl-source/dns/default.nix

    31|   writeZone = name: zone:
    32|     pkgs.writeTextFile {
      |     ^
    33|       name = "${name}.zone";
attribute 'writeTextFile' missing
```

`writeZone` seems to be the only part of nix-dns that accesses something out of `pkgs.lib` (which in flake mode is the `lib` output of the Nixpkgs flake) and that's why only it breaks.

**Comment by ncfavier** [comment]
Hm. And there's no way to actually import `nixpkgs` in pure mode without specifying what system we're running on, which the `lib` flake attribute doesn't support.

Maybe we could use `builtins.toFile` instead of `pkgs.writeTextFile`, as the zone shouldn't depend on any derivations?

**Comment by kirelagin** [comment]
Hmmmm, I think the correct solution here would be to move `writeZone` out of the `lib` output into some other output and do the full `eachDefaultSystem` dance.
